/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    post: operations["UsersController_createUser"];
  };
}

export interface components {
  schemas: {
    CreateUserDto: {
      /** @example john@gmail.com */
      email: string;
      /** @example John12345 */
      password: string;
      /** @example John Smith */
      fullName: string;
    };
    UserDto: {
      /** @example 10 */
      id: number;
      /** @example john@gmail.com */
      email: string;
      /** @example John */
      firstName?: string;
      /** @example Smith */
      lastName?: string | null;
    };
  };
}

export interface operations {
  UsersController_createUser: {
    parameters: {};
    responses: {
      /** The user has been created. */
      201: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
  };
}

export interface external {}
