/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    post: operations["UsersController_createUser"];
  };
  "/users/activation": {
    post: operations["UsersController_activeUser"];
  };
}

export interface components {
  schemas: {
    CreateUserDto: {
      /** @example john@gmail.com */
      email: string;
      /** @example John12345 */
      password: string;
      /** @example John Smith */
      fullName: string;
    };
    UserDto: {
      /** @example 10 */
      id: number;
      /** @example john@gmail.com */
      email: string;
      /** @example John */
      firstName?: string;
      /** @example Smith */
      lastName?: string | null;
    };
    OpenAPIHttpException: {
      statusCode: number;
      message: string;
      error?: string;
    };
    TokenRequestDto: {
      token: string;
    };
  };
}

export interface operations {
  UsersController_createUser: {
    parameters: {};
    responses: {
      /** The user has been created. */
      201: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      409: {
        content: {
          "application/json": components["schemas"]["OpenAPIHttpException"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
  };
  UsersController_activeUser: {
    parameters: {};
    responses: {
      204: never;
      400: {
        content: {
          "application/json": components["schemas"]["OpenAPIHttpException"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRequestDto"];
      };
    };
  };
}

export interface external {}
